---
time: '2022-01-25'
Cube:
- currency: USD
  rate: '1.1268'
- currency: JPY
  rate: '128.49'
- currency: BGN
  rate: '1.9558'
- currency: CZK
  rate: '24.5'
- currency: DKK
  rate: '7.4437'
- currency: GBP
  rate: '0.83713'
- currency: HUF
  rate: '359.44'
- currency: PLN
  rate: '4.5751'
- currency: RON
  rate: '4.9448'
- currency: SEK
  rate: '10.502'
- currency: CHF
  rate: '1.0364'
- currency: ISK
  rate: '146'
- currency: NOK
  rate: '10.1385'
- currency: HRK
  rate: '7.5295'
- currency: RUB
  rate: '88.7384'
- currency: TRY
  rate: '15.2723'
- currency: AUD
  rate: '1.5814'
- currency: BRL
  rate: '6.2049'
- currency: CAD
  rate: '1.4247'
- currency: CNY
  rate: '7.1325'
- currency: HKD
  rate: '8.7725'
- currency: IDR
  rate: '16169.54'
- currency: ILS
  rate: '3.5898'
- currency: INR
  rate: '84.277'
- currency: KRW
  rate: '1350.71'
- currency: MXN
  rate: '23.2909'
- currency: MYR
  rate: '4.7213'
- currency: NZD
  rate: '1.6911'
- currency: PHP
  rate: '57.753'
- currency: SGD
  rate: '1.5157'
- currency: THB
  rate: '37.28'
- currency: ZAR
  rate: '17.2669'
